import logging


class Config:
    APP_LOG_LEVEL = logging.INFO

    PUZZLE_MAX_COLUMNS = 25

    PUZZLE_MAX_DENSITY = 0.50
    PUZZLE_MIN_DENSITY = 0.30
    PUZZLE_MAX_PLACEMENT_ATTEMPTS = 10000
    PUZZLE_ENABLE_PROFANITY_FILTER = False

    PRINT_DPI = 200
    PRINT_PAGE_HEIGHT_INCHES = 9.61
    PRINT_PAGE_WIDTH_INCHES = 6.69
    PRINT_TOP_MARGIN_INCHES = 0.25
    PRINT_BOTTOM_MARGIN_INCHES = 0.25
    PRINT_OUTER_MARGIN_INCHES = 0.25
    PRINT_INNER_MARGIN_INCHES = 0.75

    PRINT_PAGE_HEIGHT_PIXELS = int(PRINT_PAGE_HEIGHT_INCHES * PRINT_DPI)
    PRINT_PAGE_WIDTH_PIXELS = int(PRINT_PAGE_WIDTH_INCHES * PRINT_DPI)
    PRINT_TOP_MARGIN_PIXELS = int(PRINT_TOP_MARGIN_INCHES * PRINT_DPI)
    PRINT_BOTTOM_MARGIN_PIXELS = int(PRINT_BOTTOM_MARGIN_INCHES * PRINT_DPI)
    PRINT_OUTER_MARGIN_PIXELS = int(PRINT_OUTER_MARGIN_INCHES * PRINT_DPI)
    PRINT_INNER_MARGIN_PIXELS = int(PRINT_INNER_MARGIN_INCHES * PRINT_DPI)

    PRINT_CONTENT_HEIGHT_PIXELS = PRINT_PAGE_HEIGHT_PIXELS - PRINT_TOP_MARGIN_PIXELS - PRINT_BOTTOM_MARGIN_PIXELS
    PRINT_CONTENT_WIDTH_PIXELS = PRINT_PAGE_WIDTH_PIXELS - PRINT_INNER_MARGIN_PIXELS - PRINT_OUTER_MARGIN_PIXELS

    PRINT_TITLE_BOX_HEIGHT_INCHES = 1.0
    PRINT_TITLE_BOX_HEIGHT_PIXELS = int(PRINT_TITLE_BOX_HEIGHT_INCHES * PRINT_DPI)
    PRINT_TITLE_FONT_SIZE = int(PRINT_TITLE_BOX_HEIGHT_PIXELS * 0.3)

    PRINT_WORDLIST_BOX_HEIGHT_INCHES = 2.0
    PRINT_WORDLIST_BOX_HEIGHT_PIXELS = int(PRINT_WORDLIST_BOX_HEIGHT_INCHES * PRINT_DPI)
    PRINT_WORDLIST_FONT_SIZE = PRINT_WORDLIST_BOX_HEIGHT_PIXELS // 13
    PRINT_WORDLIST_LINE_SPACING_PIXELS = 4

    PRINT_BOARD_WIDTH = PRINT_CONTENT_WIDTH_PIXELS
    PRINT_BOARD_HEIGHT = PRINT_CONTENT_HEIGHT_PIXELS - PRINT_TITLE_BOX_HEIGHT_PIXELS - PRINT_WORDLIST_BOX_HEIGHT_PIXELS
    PRINT_BOARD_HEIGHT_TWO_PAGE = PRINT_CONTENT_HEIGHT_PIXELS - PRINT_TITLE_BOX_HEIGHT_PIXELS

    PRINT_GRID_PAD_INCHES = 0.0  # from the edge of the content box to the borderline
    PRINT_GRID_PAD_PIXELS = int(PRINT_GRID_PAD_INCHES * PRINT_DPI)
    PRINT_GRID_BORDER_INCHES = 0.05  # min vlue for KDP is 0.0125
    PRINT_GRID_BORDER_PIXELS = int(PRINT_GRID_BORDER_INCHES * PRINT_DPI)
    PRINT_GRID_BORDER_RADIUS = 40
    PRINT_GRID_MARGIN_INCHES = 0.25  # from the inside fo the border to the edge of the grid
    PRINT_GRID_MARGIN_PIXELS = int(PRINT_GRID_MARGIN_INCHES * PRINT_DPI)
    PRINT_GRID_WIDTH = (
        PRINT_CONTENT_WIDTH_PIXELS
        - (2 * PRINT_GRID_PAD_PIXELS)
        - (2 * PRINT_GRID_BORDER_PIXELS)
        - (2 * PRINT_GRID_MARGIN_PIXELS)
    )
    PRINT_GRID_HEIGHT = (
        PRINT_CONTENT_HEIGHT_PIXELS
        - (2 * PRINT_GRID_PAD_PIXELS)
        - (2 * PRINT_GRID_BORDER_PIXELS)
        - (2 * PRINT_GRID_MARGIN_PIXELS)
        - PRINT_WORDLIST_BOX_HEIGHT_PIXELS
        - PRINT_TITLE_BOX_HEIGHT_PIXELS
    )
    PRINT_GRID_HEIGHT_TWO_PAGE = (
        PRINT_CONTENT_HEIGHT_PIXELS
        - (2 * PRINT_GRID_PAD_PIXELS)
        - (2 * PRINT_GRID_BORDER_PIXELS)
        - (2 * PRINT_GRID_MARGIN_PIXELS)
        - PRINT_TITLE_BOX_HEIGHT_PIXELS
    )

    PRINT_MIN_CELL_SIZE = PRINT_GRID_WIDTH // PUZZLE_MAX_COLUMNS
    PRINT_MAX_CELL_SIZE = 2 * PRINT_MIN_CELL_SIZE
    PRINT_CELL_FONT_SIZE_INCHES = 0.177
    PRINT_CELL_FONT_SIZE_PIXELS = int(PRINT_CELL_FONT_SIZE_INCHES * PRINT_DPI)
    PRINT_SOLUTION_OVERLAP = PRINT_MAX_CELL_SIZE // 10

    PUZZLE_MAX_ROWS = PRINT_GRID_HEIGHT_TWO_PAGE // PRINT_MIN_CELL_SIZE
