import logging


class Config:
    LOG_LEVEL = logging.INFO
    MAX_PUZZLE_WIDTH = 25
    MAX_PUZZLE_HEIGHT = 40
    MAX_PUZZLE_DENSITY = 0.50
    MIN_PUZZLE_DENSITY = 0.30
    MAX_PLACEMENT_ATTEMPTS = 10000
    PRINT_DPI = 200
    PRINT_TOP_MARGIN = 0.25
    PRINT_BOTTOM_MARGIN = 0.25
    PRINT_OUTER_MARGIN = 0.25
    PRINT_INNER_MARGIN = 0.45
    PAGE_HEIGHT = 9.61
    PAGE_WIDTH = 6.69
    PRINTABLE_HEIGHT = PAGE_HEIGHT - PRINT_TOP_MARGIN - PRINT_BOTTOM_MARGIN
    PRINTABLE_WIDTH = PAGE_WIDTH - PRINT_OUTER_MARGIN - PRINT_INNER_MARGIN
    PIXELS_HEIGHT = int(PRINTABLE_HEIGHT * PRINT_DPI)
    PIXELS_WIDTH = int(PRINTABLE_WIDTH * PRINT_DPI)
